version: "3.1"
services:
  saasform:
    image: saasform/saasform:latest
    restart: always
    depends_on:
      - saasform-db
    environment:
      - NODE_ENV=development
      - MYSQL_HOST=saasform-db
      - MYSQL_DATABASE=saasform
      - MYSQL_USER=saasform
      - MYSQL_PASSWORD=saasformp
    ports:
      - "7000:7000"
    volumes:
      - ./data/config:/app/config
      - ./data/themes:/app/themes

  saasform-db:
    image: mariadb:10.5
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=saasform
      - MYSQL_USER=saasform
      - MYSQL_PASSWORD=saasformp
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./data/db:/var/lib/mysql:cached

  demo-express:
    image: saasform/demo-express:latest
    depends_on:
      - saasform
    environment:
      SAASFORM_SERVER: http://saasform:7000
      SAASFORM_USER_LOGIN: http://localhost:7000/login
    ports:
      - "3000:3000"
    command: ["wait-for-it", "webapp:7000", "--", "npm", "start"]
