version: "3.1"
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./src/webapp/env/env.local
    ports:
      - "3306:3306"
    volumes:
      - ./data/db:/var/lib/mysql:cached

  webapp:
    image: saasform
    restart: always
    depends_on:
      - db
    env_file:
      - ./src/webapp/env/env.local
    environment:
      MYSQL_HOST: db
    ports:
      - "3000:3000"
    volumes:
      - ./data/themes:/app/themes

  # admin:
  #   image: node:12
  #   restart: always
  #   depends_on:
  #     - webapp
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ./admin:/mnt:cached
  #   working_dir: /mnt
  #   command: yarn start
