version: "3.1"
services:
  saasform:
    image: saasform:latest
    restart: always
    depends_on:
      - saasform-db
    env_file:
      - ./data/saasform.env
    ports:
      - "7000:7000"
    volumes:
      - ./data/config:/app/config
      - ./data/themes:/app/themes

  saasform-db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./data/saasform.env
    volumes:
      - ./data/db:/var/lib/mysql:cached

  demo-express:
    image: demo-express:latest
    depends_on:
      - saasform
    environment:
      SAASFORM_SERVER: http://saasform:7000
      SAASFORM_USER_LOGIN: http://localhost:7000/login
    ports:
      - "3000:3000"
    command: ["wait-for-it", "webapp:7000", "--", "npm", "start"]
