SAAS_REDIRECT_URL: http://localhost:3000
SAASFORM_BASE_URL: http://localhost:7000

MYSQL_HOST: localhost
MYSQL_PORT: 3306
MYSQL_DATABASE: saasform
MYSQL_USER: saasform
MYSQL_PASSWORD: saasformp

## WARNING: remove this for production
NODE_ENV: development

# UPDATE THE FOLLOWING VALUES
SENDGRID_API_KEY: SG.xxx
SENDGRID_SEND_FROM: hello@beautifulsaas.com

STRIPE_API_KEY: sk_xxx
